#!/bin/sh

set -e

case "$1" in
  configure)
    xdg-desktop-menu install /usr/share/desktop-directories/netrunner-web.directory /usr/share/applications/hooktube.desktop --novendor
    xdg-desktop-menu install /usr/share/desktop-directories/netrunner-web.directory /usr/share/applications/telegram.desktop --novendor
    xdg-desktop-menu install /usr/share/desktop-directories/netrunner-web.directory /usr/share/applications/whatsapp.desktop --novendor
esac

#DEBHELPER#

exit 0
