#!/bin/sh

set -e

case "$1" in
  remove)
    xdg-desktop-menu uninstall /usr/share/desktop-directories/netrunner-web.directory /usr/share/applications/hooktube.desktop
    xdg-desktop-menu uninstall /usr/share/desktop-directories/netrunner-web.directory /usr/share/applications/telegram.desktop
    xdg-desktop-menu uninstall /usr/share/desktop-directories/netrunner-web.directory /usr/share/applications/whatsapp.desktop
    xdg-desktop-menu uninstall /usr/share/desktop-directories/netrunner-web.directory /usr/share/applications/skype-web.desktop
    xdg-desktop-menu uninstall /usr/share/desktop-directories/netrunner-web.directory /usr/share/applications/opendesktop.desktop
esac

#DEBHELPER#

exit 0
